### ISSUE TITLE
dtcw.ps1 parsing and other errors

### ISSUE THREAD

**Issue by pln-rec** [docToolchain/doctoolchain.github.io#11]
Hi!

I just tested docToolChain 2.0 with the new wrapper and found that it does not run ootb (`dtcw - docToolchain wrapper V0.18 (PS)`). A closing bracket is missing (no Docker is installed on my Windows system):
``` 
PS C:\Workspace\archdocu2> ./dtcw.ps1 generateHtml
At C:\Workspace\archdocu2\dtcw.ps1:116 char:6
+ else {
+      ~
Missing closing '}' in statement block or type definition.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : MissingEndCurlyBrace
```

After fixing this, I encountered the next problem:
```
Test-Path : Cannot bind argument to parameter 'Path' because it is null.
At C:\Workspace\archdocu2\dtcw.ps1:121 char:23
+         if (Test-Path $FolderName) {
+                       ~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Test-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.TestPathCom
   mand
```
I assumed that instead of `if (Test-Path $FolderName)`, it needs to be `if (Test-Path $home_path)`.
With this change, the download succeeds and the script is able to run.

**Comment by rdmueller** [comment]
thanx for reporting this.
I have now even removed the `if (Test-Path $FolderName) {` - I think it is not necessary.
I'll re-test as soon as the change is available on github pages

**Comment by rdmueller** [comment]
works for me now. for you also?

**Comment by pln-rec** [comment]
@rdmueller Yes, works as expected (deleted the dtc distribution first). 

Thanks for this awesome project anyways!
