### ISSUE TITLE
dtcw effectively not running in non-interactive mode

### ISSUE THREAD

**Issue by ascheman** [docToolchain/doctoolchain.github.io#24]
Looks like `dtcw` is maintained here (why? I am always confused ;-)).

Cf. doctoolchain/doctoolchain#867 for the bug report.

**Comment by rdmueller** [comment]
good point. We should copy it over to the main repository and only deploy it here.

**Comment by rdmueller** [comment]
we need some kind of deployment token for doing so, don't we?
I'm not sure if I can do this in the near future...

maybe in a pair programming session?

**Comment by rdmueller** [comment]
I think we already fixed this, didn't we?
