### ISSUE TITLE
docToolchain wrapper is unable to find docker image for rc14

### ISSUE THREAD

**Issue by danielkocot** [docToolchain/doctoolchain.github.io#6]
**Describe the bug**
The wrapper is unable to find docker image for [rc14.]

**Expected behavior**
Find docker image and use the docker installation.

**Screenshots**
<img width="1194" alt="CleanShot 2021-08-02 at 16 18 56@2x" src="https://user-images.githubusercontent.com/466609/127876672-642c3fb0-78f2-4121-8c6a-abd63bc7232f.png">

**Configuration**
 - OS: Apple

**Comment by rdmueller** [comment]
quick fix: use rc13
long fix: the docker container has version rc14**b** :-( 
the current wrapper should already have rc14b in the code. I guess you upgraded yourself?

**Comment by danielkocot** [comment]
I used the downloaded revision directly. The issue is more a reminder to have it in mind ;). So I will close it for now.
